esphome:
  name: esp32c3-device1

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:
  level: WARN

packages:
  wifi: !include common/wifi.yaml
  api: !include common/api.yaml
  ota: !include common/ota.yaml

sensor:
  - platform: internal_temperature
    name: "Device1 Internal Temperature"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    name: "Device1 Button"
