name: Build & Release ESPHome firmware

on:
  push:
    tags:
      - 'v*'   # запуск только на теги вида v1.0.0

permissions:
  contents: write

jobs:
  build:
    name: Compile firmware
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Установка ESPHome 2026.1.5
      - name: Install ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install e
